adx_contentsnippetid: 7967ce3f-fcb6-ea11-a812-000d3a1ab88b
adx_contentsnippetlanguageid: d9e7ed64-7337-47a8-af6e-35a783c2e2dd
adx_display_name: Application/CPF/CanadianEditorialExpenses
adx_name: Application/CPF/CanadianEditorialExpenses
adx_type: 756150001
