adx_contentsnippetid: 9a79d44b-fcb6-ea11-a812-000d3a1ab88b
adx_contentsnippetlanguageid: 02e43fff-d17a-ea11-a811-000d3af422f3
adx_display_name: Application/CPF/CanadianEditorialExpenses
adx_name: Application/CPF/CanadianEditorialExpenses
adx_type: 756150001
