adx_contentsnippetid: 47db2c39-3fa8-ea11-a812-000d3a8b3e5a
adx_contentsnippetlanguageid: d9e7ed64-7337-47a8-af6e-35a783c2e2dd
adx_display_name: Application/Funding/Ineligible
adx_name: Application/Funding/Ineligible
