adx_contentsnippetid: 76fc1c72-3fa8-ea11-a812-000d3a8b3e5a
adx_contentsnippetlanguageid: 02e43fff-d17a-ea11-a811-000d3af422f3
adx_display_name: Application/Funding/Ineligible
adx_name: Application/Funding/Ineligible
