adx_contentsnippetid: 3aee2ad2-f27c-ea11-a811-000d3af422f3
adx_contentsnippetlanguageid: d9e7ed64-7337-47a8-af6e-35a783c2e2dd
adx_display_name: Home/MyApplicationsTable/Header2
adx_name: Home/MyApplicationsTable/Header2
