adx_contentsnippetid: 61dce903-c722-eb11-a813-000d3af413df
adx_contentsnippetlanguageid: d9e7ed64-7337-47a8-af6e-35a783c2e2dd
adx_name: Security Screening Application/Tab/Instructions/TAB_Review_and_release_to_applicant
