adx_displayorder: 15
adx_enablerating: false
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_isroot: true
adx_name: Application - View Attestation
adx_pagetemplateid: 614d9ec8-4c6a-ea11-a812-000d3af42f4a
adx_parentpageid: 87cdfb86-e3c8-48d7-8a99-c6fb2cbcb845
adx_partialurl: view-attestation
adx_publishingstateid: 38c7d71a-31fd-4c2a-b7b0-fa2cc7381654
adx_rootwebpageid: ccb3a037-0baa-ea11-a812-000d3a8b3e5a
adx_sharedpageconfiguration: true
adx_title: Fonds d'urgence - Attestation
adx_webpageid: c1290548-0baa-ea11-a812-000d3a8b3e5a
adx_webpagelanguageid: 02e43fff-d17a-ea11-a811-000d3af422f3
statecode: 1
statuscode: 2
