adx_contentsnippetid: 916404c3-fb13-eb11-a813-000d3af46865
adx_contentsnippetlanguageid: d9e7ed64-7337-47a8-af6e-35a783c2e2dd
adx_display_name: Security Screening Application/Security Level
adx_name: Security Screening Application/pspc_securitylevelsecuritylevelid
