adx_calendar_enabled: false
adx_detailsbuttonlabel: >-
  [
    {
      "LCID": 1033,
      "Value": "test"
    },
    {
      "LCID": 1036,
      "Value": "test"
    }
  ]
adx_entitylistid: 042135f3-4807-eb11-a813-000d3af413df
adx_entityname: contact
adx_entitypermissionsenabled: false
adx_filter_enabled: false
adx_idquerystringparametername: id
adx_map_distancevalues: 5,10,25,50,100
adx_map_enabled: false
adx_map_infoboxoffsetx: 25
adx_map_infoboxoffsety: 46
adx_map_pushpinheight: 39
adx_map_pushpinwidth: 32
adx_map_resturl: https://dev.virtualearth.net/REST/v1/Locations
adx_map_zoom: 12
adx_name: CSP - Security Screening Application - My Employees
adx_odata_enabled: false
adx_pagesize: 10
adx_searchenabled: true
adx_settings: >-
  {
    "Type": "CrmEntityFormView-GridMetadata",
    "ViewFormats": [],
    "ViewActions": [],
    "ExtendedViewActions": [],
    "ItemActions": [
      {
        "Type": "CrmEntityFormView-DetailsAction",
        "RecordIdQueryStringParameterName": "cid",
        "TargetType": 1,
        "OnComplete": 0,
        "RedirectWebpageId": "d204e7d6-a008-eb11-a813-000d3af46865",
        "RedirectUrl": "",
        "EntityFormId": "",
        "ShowModal": 0,
        "Confirmation": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": ""
          },
          {
            "Type": "LanguageResources",
            "LCID": 1036,
            "Value": ""
          }
        ],
        "SuccessMessage": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": ""
          },
          {
            "Type": "LanguageResources",
            "LCID": 1036,
            "Value": ""
          }
        ],
        "ButtonLabel": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": "View Security Assessment Applications"
          },
          {
            "Type": "LanguageResources",
            "LCID": 1036,
            "Value": ""
          }
        ],
        "ButtonTooltip": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": ""
          },
          {
            "Type": "LanguageResources",
            "LCID": 1036,
            "Value": ""
          }
        ],
        "ActionIndex": 0,
        "FilterCriteria": ""
      }
    ],
    "ExtendedItemActions": [],
    "ColumnOverrides": [],
    "LoadingMessage": [
      {
        "Type": "LanguageResources",
        "LCID": 1033,
        "Value": ""
      },
      {
        "Type": "LanguageResources",
        "LCID": 1036,
        "Value": ""
      }
    ],
    "ErrorMessage": [
      {
        "Type": "LanguageResources",
        "LCID": 1033,
        "Value": ""
      },
      {
        "Type": "LanguageResources",
        "LCID": 1036,
        "Value": ""
      }
    ],
    "AccessDeniedMessage": [
      {
        "Type": "LanguageResources",
        "LCID": 1033,
        "Value": ""
      },
      {
        "Type": "LanguageResources",
        "LCID": 1036,
        "Value": ""
      }
    ],
    "EmptyMessage": [
      {
        "Type": "LanguageResources",
        "LCID": 1033,
        "Value": ""
      },
      {
        "Type": "LanguageResources",
        "LCID": 1036,
        "Value": ""
      }
    ],
    "DetailsFormDialog": {
      "Type": "CrmEntityFormView-DetailsFormModal",
      "LoadingMessage": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "Size": 1,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "EditFormDialog": {
      "Type": "CrmEntityFormView-EditFormModal",
      "LoadingMessage": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "Size": 1,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "CreateRelatedRecordDialog": {
      "Type": "CreateRelatedRecordModal",
      "LoadingMessage": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "Size": 1,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "CreateFormDialog": {
      "Type": "CrmEntityFormView-CreateFormModal",
      "LoadingMessage": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "Size": 1,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "DeleteDialog": {
      "Type": "CrmEntityFormView-GridDeleteModal",
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "Size": 0,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "WorkflowDialog": {
      "Type": "WorkflowModal",
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "Size": 0,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "ErrorDialog": {
      "Type": "CrmEntityFormView-ErrorModal",
      "Body": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "Size": 0,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "CssClass": "",
    "GridCssClass": "table-striped",
    "GridColumnWidthStyle": 1,
    "ActivateDialog": {
      "Type": "ActivateModal",
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "Size": 0,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "DeactivateDialog": {
      "Type": "DeactivateModal",
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "Size": 0,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "GetDirectionsDialog": {
      "Type": "GetDirectionsModal",
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        },
        {
          "Type": "LanguageResources",
          "LCID": 1036,
          "Value": ""
        }
      ],
      "Size": 1,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    }
  }
adx_view: db7c9e78-f807-eb11-a813-000d3af46865
adx_views: >-
  {
    "Type": "ViewMetadata",
    "Views": [
      {
        "Type": "View",
        "ViewId": "db7c9e78-f807-eb11-a813-000d3af46865",
        "DisplayName": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": "My Employees"
          },
          {
            "Type": "LanguageResources",
            "LCID": 1036,
            "Value": ""
          }
        ]
      }
    ]
  }
statecode: 1
statuscode: 2
