adx_displayorder: 1
adx_enablerating: false
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_isroot: true
adx_name: config
adx_pagetemplateid: 5550c092-af5e-44e1-8c35-2e98fe4cd830
adx_parentpageid: c259b430-9468-ea11-a812-000d3af422f3
adx_partialurl: config
adx_publishingstateid: 38c7d71a-31fd-4c2a-b7b0-fa2cc7381654
adx_sharedpageconfiguration: true
adx_webpageid: 03e9d04f-9568-ea11-a812-000d3af422f3
