adx_contentsnippetid: 52e2238f-0d90-ea11-a811-000d3a1ab88b
adx_contentsnippetlanguageid: 02e43fff-d17a-ea11-a811-000d3af422f3
adx_display_name: Home/NewApplicationButton
adx_name: Home/NewApplicationButton
