adx_enablerating: false
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_isroot: false
adx_name: CSP - Security Screening Application - [B] Background information - ReadOnly
adx_pagetemplateid: 4d70cb7a-b0fd-ea11-a813-000d3af46865
adx_partialurl: background-information
adx_publishingstateid: 38c7d71a-31fd-4c2a-b7b0-fa2cc7381654
adx_sharedpageconfiguration: true
adx_title: '[B] Background information'
adx_webpageid: 6afac352-880e-eb11-a813-000d3af413df
adx_webpagelanguageid: d9e7ed64-7337-47a8-af6e-35a783c2e2dd
